version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - terraform
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t alvaroalmanza/django-app:$CIRCLE_BRANCH -f ./0-app/Dockerfile .

     # deploy the image
     - run: docker push alvaroalmanza/django-app:$CIRCLE_BRANCH