version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: echo "$DOCKER_PASS" | sudo docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t alvaroalmanza/stylesage:$CIRCLE_BRANCH -f 0-app/Dockerfile .

     # deploy the image
     - run: docker push alvaroalmanza/stylesage:$CIRCLE_BRANCH