version: 2.1
orbs:
  terraform: circleci/terraform@3.0.0
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0

workflows:
  my-workflow:
    jobs:
      - build-docker-app:
          context:
            - terraform
      - deploy-ias:
          requires:
            - build-docker-app
          context:
            - terraform
      - create-deployment:
          requires:
            - deploy-ias
          context:
            - terraform

jobs:
  build-docker-app:
    machine: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      # build the application image
      - run: docker build -t alvaroalmanza/django-app:$CIRCLE_BRANCH -f ./0-app/Dockerfile .

      # deploy the image
      - run: docker push alvaroalmanza/django-app:$CIRCLE_BRANCH

  deploy-ias:
    executor: terraform/default
    working_directory: "~/src"
    steps:
      - checkout
      - terraform/init:
          path: "./1-IAC-Terraform"
      - terraform/validate:
          path: "./1-IAC-Terraform"
      - terraform/fmt:
          path: "."
      - terraform/plan:
          path: "./1-IAC-Terraform"
          var: "deploy-name=almanza-cluster,env=dev"
      - terraform/apply:
          path: "./1-IAC-Terraform"
          var: "deploy-name=almanza-cluster,env=dev"

  create-deployment:
    executor: aws-eks/python3
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: almanza-cluster
          install-kubectl: true
          aws-region: eu-west-1
      - kubernetes/create-or-update-resource:
          get-rollout-status: false
          resource-file-path: /tmp/django_deployment.yml