  apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: django-app
    name: django-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: django-app
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: django-app
      spec:
        containers:
        - image: alvaroalmanza/stylesage:v1
          name: django-app
          env:
          - name: DJANGO_SETTINGS_MODULE
            value: iotd.settings
          - name: RDS_DB_NAME
            value: 
          - name: RDS_USERNAME
            value: 
          - name: RDS_PASSWORD
            value: 
          - name: RDS_HOSTNAME
            value:
          - name: RDS_PORT
          - name: S3_BUCKET_NAME
            value: 
          ports:
          - containerPort: 8000
---
  apiVersion: v1
  kind: Service
  metadata:
    name: django-app-service
  spec:
    selector:
      app: prisma-app
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8000
    type: LoadBalancer